### ISSUE TITLE
Provide Location Names for Coordinates

### ISSUE THREAD

**Issue by vitaovich** [DrewAGamboa/Carceral-Groups-Website#19]
Add a spreadsheet that can be used to identify coordinates with a location name.

<img width="448" alt="image" src="https://github.com/DrewAGamboa/Carceral-Groups-Website/assets/16531155/4d02ad96-cdc1-4978-a5f1-295d2f9da50a">

**Comment by DrewAGamboa** [comment]
https://docs.google.com/spreadsheets/d/1gj7zeBeBMwEDDN8WHqkYcAyccUegJGBEBfJDmZThdb8/edit#gid=0
